### ISSUE TITLE
Get Harmony Twp to recycle!

### ISSUE THREAD

**Issue by BergFulton** [Ambridge/Ambridge#13]
Harmony currently does not offer recycling to residents. We are contracted through Valley refuse at the moment, but it wasn't offered when we were with Waste Management either. Can we start a formal petition or some sort of groundswell to offer recycling to residents? It is pretty odd to me that Ambridge proper recycles - if you cross 24th st., recycling. If you go to Baden, recycling. That wedge in between? No recycling. Seems like something that most people would accept, because...well...it's not 1995? 

Anyone who can help me make this happen? I'd even be cool with a communal collection point somewhere!

**Comment by whit537** [comment]
Yay Harmony Township! I just made a label and applied it here.

**Comment by BergFulton** [comment]
We're closing things left and right- last week we got a newsletter from Harmony Twp that there will be voluntary community recycling points for plastic, glass, and paper (I believe?) at the Township building. Not curbside, but hey! Every little bit helps. 

Shut 'en er down!

**Comment by whit537** [comment]
Huzzah! :D

**Comment by pfulton** [comment]
FYI, here's the information from the newsletter:

`A voluntary recycling program will begin in May. Two recycling bins will be housed
behind the Harmony Township Volunteer Fire Department located at 2400 Beaver
Avenue. The Mixed Use Paper Products bin can be used to recycle any of the following:
Office Paper, Newspapers, Magazines, Catalogs, Envelopes, Junk Mail, School Papers,
Brown Paper Bags, Paperback Books, Computer Paper, Paperboard or Chipboard—such
as cereal boxes, pasta boxes, cracker boxes, beer and wine cooler carriers.
A separate bin will be for Corrugated Cardboard Boxes only`

And a screenshot from the PDF:

![screen shot 2015-04-21 at 10 40 12 am](https://cloud.githubusercontent.com/assets/360251/7254774/1b69bdfe-e813-11e4-81bb-eb61a5cdaa4c.png)
