### ISSUE TITLE
introduce GitHub to Ambridge boro leadership

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#18]
I have a meeting with council president Mike Mikulich and borough manager Joe Kauer on Thursday January 22, at 11am.

**Comment by whit537** [comment]
Meeting went extremely well. @jmkauer is now on GitHub and Mike invited me to give a 10-minute presentation to council at the beginning of their next executive session (Feb 10 at 6pm). That'll be a short introduction, with an offer to meet one-on-one with any interested council member to help them get signed up for GitHub. Leaving this ticket open through then.

**Comment by mmikul** [comment]
Hi Chad;

Mike here I hope I signed in ok?

**Comment by whit537** [comment]
Hah! Love it! Welcome aboard, @mmikul! :-)

**Comment by weallhave24hrs** [comment]
Hello Gentlemen

**Comment by whit537** [comment]
Intro to council went well this evening. Thank you for having me in, @mmikul @jmkauer et al.! :-)

My plan is to follow up with committee chairs to see if they're interested in getting on GitHub, perhaps joining them at their committee meetings in the coming months(?). I spoke briefly with Tina and Janet after tonight's council meeting in this regard.

**Comment by mmikul** [comment]
Chad ; It was a pleasure having you at your council meeting. Thanks for being there. It's a great idea to report to the committee meeting , that will give you a better opportunity to go forward with GitHub.

**Comment by whit537** [comment]
@mmikul Now you're getting the hang of it! Feels good to click that "Close" button, doesn't it? :D
