### ISSUE TITLE
paint the crosswalk at 10th & Duss

### ISSUE THREAD

**Issue by EileenFord** [Ambridge/Ambridge#25]
The Ambridge Area High School is a center of our community for activities - young and old alike.  Winter, Spring, Summer, Fall, this campus is the center of both our school district and the entire community.  In the summer, there is a free meal program available in the cafeteria open to all under age 18.  On any given weekend, the buildings and fields may host youth wrestling matches, basketball games, dance recitals, midget football, plays, craft shows to name a few of the regular activities and events. Evenings and after school, the high school students themselves are there for any number of practices or rehearsals.  The crosswalk, as with any school, is only monitored by our fantastic crossing guard, Kim, during the designated pre & post school times.  This intersection however is a place of danger anytime there is no crossing guard monitoring it.  I have never, once, experienced a car yielding to pedestrians in this crosswalk in all the time I have been using this crosswalk. I have had cars shout at me for crossing with a stroller, when I had the clear right of way, before they sped from the light a block away.  During the years from 2006 through 2008 I worked in the Ambridge High School office.  I was fortunate to be able to walk to work  - like many of our students.  During this period I became very familliar with the extreme dangers of the particular insection of 10th Street at Duss Ave. Not only do cars and trucks not yield to pedestrians, often cars will park in such a way to block the crosswalk and the intersection itself.  Additionally, a large amount of car and truck traffic frequently ignores the speed limit through this school zone the instance a crossing guard is no longer visible.  When cars are making turns in this intersection,  vehicles consistently and dangerously pass the stopped vehicle trying to make a turn with no regard to possible traffic pulling out or the possibility of pedestrians.
Returning to my statement of the time when I worked in the school district, I brought this intersection and the dangers prevalent to the attention of the AASD Safety Committee.  At the time, they answered my questions and concerns saying that the borough would not allow further signs in the road or restrictions due to it being on  a state route (989).  However, comparitively, another state route (51) runs through South Heights across the river & has clearer pedestrian signs and enforcement.   
The total disregard for the safety of our children, students, family members attending a game, or event, pedestrians, dog walkers, athletes and All members of this community need to be addressed.  What do we need to do to show our community that we care about their safety as they attend happenings in the hub of our district?  Let's work to get the crosswalk painted diagonally throughout the entire intersection and street standing signs, no passing signs, and just some enforcement of the yielding to pedestrians! It is a state law - and it needs to be enforced. Thanks for taking the time to read.

**Comment by JaneStads** [comment]
Do we know who controls this? Is the AASD Safety Committee have the actual authority to get it done?

**Comment by jmkauer** [comment]
Hello Ms. Ford-

Good afternoon, my name is Joe Kauer, I serve as the Ambridge Borough Manager.  Thank you for your concerns.  I personally reviewed this intersection today.  There are a a set of modern, high-intensity pedestrian crossing warning signs that are posted in either direction at this intersection.  The Borough does employee a Crossing Guard their during school hours.  I do agree with you regarding the painting of the crosswalk.  We are currently discussing purchasing a commercial grade line painting machine that will enable our Public Works Department to paint and in some areas like you state, improve the striping of the crosswalks, stop bars, turning lanes...  Come spring, once we get back into line painting, we will make sure to address this intersection.  As for a pedestrian crossing sign that would go in the roadway; we do have a couple of these signs.  To avoid issues with the snow plows, we will make sure to put one of them there come spring.   Thank you again for your concerns. 

Joe Kauer

**Comment by whit537** [comment]
Everyone see that? @jmkauer is on GitHub! :dancer: 

Welcome aboard, @jmkauer! :beers:

**Comment by whit537** [comment]
I reticketed purchasing a commercial grade line painting machine as #26.

I reticketed putting a pedestrian crossing sign in the roadway come spring as #27.

Let's leave this ticket for actually painting the crosswalk.

> some enforcement of the yielding to pedestrians! It is a state law - and it needs to be enforced.

What would the action item there be? Having a conversation with Chief Mann?

**Comment by goldbug** [comment]
Never mind painting new lines and putting up signs, how about having the police enforce pedestrian right of ways?  I'm regularly on my feet in a number of Beaver County river towns, and while they're mostly all inconsistent with observing pedestrian crosswalks and rights of way, Ambridge is in a class by itself with inconsiderate motorist refusing to yield to pedestrians.  If the goal is to draw people into the downtown area, a good start would be making it so a person didn't risk getting killed crossing the street.

**Comment by whit537** [comment]
> Never mind painting new lines and putting up signs, how about having the police enforce pedestrian right of ways?

That was mentioned in the original request, above. Per my last comment at https://github.com/Ambridge/Ambridge/issues/25#issuecomment-71078921, we need an action item. Is filing a request with the police department enough (cf. #50)? That's easy to do, of course, but doesn't actually mean that enforcement increases. How do we measure enforcement? Number of hours spent policing the intersection? Number of citations issued?

**Comment by goldbug** [comment]
This isn't a major undertaking, or it certainly shouldn't be.  I'm talking about police who are already on the job, one or two days a month, for 3 or 4 hours a day, trapping and writing citations.  They (the police) don't need to be out there constantly, and they could pick good weather days for all I care.  Do that 3 or 4 times and word will get out that Ambridge police are serious about enforcing pedestrian right of ways.  It's not the number of tickets written, it's being visable and writing tickets just a few times to do the trick.

**Comment by whit537** [comment]
Okay @goldbug, reticketed as #51. Thanks for the input! :-)

**Comment by whit537** [comment]
From @EileenFord at https://github.com/Ambridge/Ambridge/issues/26#issuecomment-127637523:

> I assume  you will diagonal line paint the Entire intersection at 10th and Duss, as the 2 pedestrian crossing signs in the crosswalks never happened successfully. The 1 (one ) that showed up was stolen within 2 weeks. They truly need to be anchored permanently. Despite plow truck ease - Pedestrian safety & obedience  to state law is paramount.

**Comment by whit537** [comment]
This did in fact get done.
