### ISSUE TITLE
purchase a commercial grade line painting machine

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#26]
Reticketed from https://github.com/Ambridge/Ambridge/issues/25#issuecomment-71074719:

> We are currently discussing purchasing a commercial grade line painting machine that will enable our Public Works Department to paint and in some areas like you state, improve the striping of the crosswalks, stop bars, turning lanes...

**Comment by whit537** [comment]
cc: @eileenford @jmkauer

**Comment by whit537** [comment]
Council approved the purchase of a [Linelazer 3400](http://www.graco.com/us/en/products/contractor/linelazer-3400.html) last night. @jmkauer Can you let us know when that purchase is complete?

**Comment by jmkauer** [comment]
Will do.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
What's the status on this, @jmkauer? Do we have the Linelazer in hand now?

**Comment by jmkauer** [comment]
Good Morning!

The new line painter is in and in-service.  DPW started line painting of
the public parking lots and worked extensively on Merchant Street last
week.  Line painting will resume next week on Duss Avenue and throughout
the Borough.

Thanks for checking in.

Joe


Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Street
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by EileenFord** [comment]
I assume  you will diagonal line paint the Entire intersection at 10th and Duss, as the 2 pedestrian crossing signs in the crosswalks never happened successfully. The 1 (one ) that showed up was stolen within 2 weeks. They truly need to be anchored permanently. Despite plow truck ease - Pedestrian safety & obedience  to state law is paramount. 
On Aug 3, 2015 11:03 AM, jmkauer <notifications@github.com> wrote:Good Morning!

The new line painter is in and in-service.  DPW started line painting of
the public parking lots and worked extensively on Merchant Street last
week.  Line painting will resume next week on Duss Avenue and throughout
the Borough.

Thanks for checking in.

Joe


Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Street
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Thanks for the update, @jmkauer! Closing this ticket as completed.

@EileenFord I've copied your comments over to https://github.com/Ambridge/Ambridge/issues/25#issuecomment-128885378.
