### ISSUE TITLE
put a pedestrian crossing sign in the 10th and Duss intersection

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#27]
Reticketed from https://github.com/Ambridge/Ambridge/issues/25#issuecomment-71074719:

> As for a pedestrian crossing sign that would go in the roadway; we do have a couple of these signs. To avoid issues with the snow plows, we will make sure to put one of them there come spring.

cc: @eileenford @jmkauer

**Comment by jmkauer** [comment]
As promised Ambridge DPW put out the Pedestrian Crossing Sign today at this location.  Thanks for your patience!

Joe Kauer
Borough Manager

**Comment by sbdavies** [comment]
Thank you very much for following up!
