### ISSUE TITLE
Parking restrictions for Corner of 24th and Lenz.

### ISSUE THREAD

**Issue by BergFulton** [Ambridge/Ambridge#32]
If you're trying to turn off of Lenz and on to 24th Street, the cars that are parked right up to the corner make it impossible to seem traffic heading down 24th towards the Duss Ave. light. If parking was restricted back from the corner, it could help improve visibility for drivers and pedestrians. I have to make this turn in my car every day, and the number of near misses is terrifying, and again, as a regular runner and walker, the same is also true for being on foot.

**Comment by mmikul** [comment]
If I think what you are saying is correct, then you are making a right hand turn on 24th St to go to the 24th red light on Duss. If this is correct then the cars you are talking about are in Harmony Twp. and they have to make that call. Remember when you travel up 24th street, on the right hand side is Ambridge and the left hand side is Harmony Twp.

Thanks

**Comment by BergFulton** [comment]
Yes, that's exactly what I'm talking about. I'm hoping @whit537 's (or someone else from the group's) conversations with Harmony Twp regarding GitHub and issue tracking can help get this solved. Because of my commute, I will never be able to make a Harmony Twp meeting, unfortunately, or I'd have been lobbing this and the recycling ticket for three years.

**Comment by mmikul** [comment]
I would be happy to forward it on to Harmony Twp  officials for you.

thanks

**Comment by whit537** [comment]
@BergFulton Let's pick up on #21 with introducing GitHub to Harmony Twp leadership.

**Comment by BergFulton** [comment]
Went for a run this morning- noticed that the curb at this corner has a nice brand new BRIGHT YELLOW no parking strip painted! Woohoo! I don't know when this happened, because I've been traveling for work for the last...forever...but at any rate, great job, Harmony! Going to go ahead and close this one.

**Comment by whit537** [comment]
Nice! :runner:
