### ISSUE TITLE
introduce GitHub to Rep Matzie

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#33]
Reticketing from https://github.com/Ambridge/Ambridge/issues/31#issuecomment-71736413. Matzie should be aware of what we're doing here. I just called and left a message with his office, asking to schedule an appointment with him.

**Comment by whit537** [comment]
Who else should I reach out to to make sure they know about this?

**Comment by mmikul** [comment]
he is aware 

----- Original Message -----

**Comment by whit537** [comment]
@mmikul Excellent, thank you. I have an appointment scheduled for February 18 at 11:00 AM. I'm also scheduled to be with the Rotary Club that morning and will at least mention GitHub there (I'm primarily there to share about my company, Gratipay).

**Comment by rmatzie** [comment]
Just set up my account.  Good meeting and introduction to this exciting platform!

**Comment by whit537** [comment]
Welcome aboard, @rmatzie! :D

**Comment by Hiznolly** [comment]
Rob, welcome to GitHub.  I just joined last night.  Looking forward to this platform improving the communication and process of getting things done for the good.

Paul Mitchell 
President
AACC
