### ISSUE TITLE
host someone from GitHub

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#38]
Using GitHub for local civic engagement is somewhat novel, and, I believe, potentially interesting to GitHub themselves. [To wit](https://twitter.com/raganwald/status/566403485826969602):

> The citizens of Ambridge, PA organize with @github. That is sooooooooo cool!

It would be great for our town if a representative from GitHub were to visit.

**Comment by whit537** [comment]
cc: @raganwald ;-)

**Comment by whit537** [comment]
Aaaaaand I just discovered this response from @defunkt (co-founder and CEO of GitHub) in private email:

> Wow, this is incredible. We have our weekly all hands meeting in 40 minutes and I'm going to tell the whole company about this. Thank you for emailing me!

:-)

For the record, here's the mail I sent to him:

>I'm writing to let you know that the town of Ambridge, PA, is now officially using GitHub as a way to engage with citizens:
>
> http://www.ambridgeboro.org/index.asp?Type=B_BASIC&SEC={664BA0C4-2F8F-43B4-A42B-F118C8DF7B81}&DE={662B9E1E-AB4F-43C0-BF77-97A18507F235}
>
>I use GitHub to run my company, Gratipay, and a couple months ago I decided to set up a repo for my town. I've been really encouraged by the response of our local government, which is all the more interesting because these are not hip youngsters we're talking about. Ambridge is a quintessential rust belt town with quintessential rust belt leadership. If GitHub can help improve governance here in Ambridge, it can help anywhere.
>
> https://github.com/Ambridge/Ambridge
>
>Keep up the great work on GitHub! :D

Although now that you're using GitHub, @mmikul, I might have to revise my assessment of your hipness. ;-)

**Comment by raganwald** [comment]
I can neither confirm nor deny that I discovered the town of Ambridge during the company all-hands meeting, however I do believe that several neighbours reported hearing loud cheering during the all-hands on Friday evening.

:clap:

**Comment by BergFulton** [comment]
...so we're officially cool then? Right? 

This is awesome! :+1:

**Comment by whit537** [comment]
@raganwald Hah! :D Well, we'd love to have you down some time this year if it fits your schedule. Looks like the last Pittsburgh-area drinkup was [a couple years ago](https://github.com/blog/1425-pittsburgh-drinkup)?

Here's [a recent write-up](https://medium.com/gratipay-blog/meet-ambridge-8b9b2b6f8628) I did about Ambridge, if you want a little more background. For a deep dive check out www.ambridgeconnection.com from @weallhave24hrs.

Let us know if you're interested! :-)

P.S. chad@zetaweb.com or +1-412-925-4220 if you want to discuss privately.

**Comment by raganwald** [comment]
I’d be delighted to visit some time, but there are outstanding ‘hubbers in your area!

**Comment by whit537** [comment]
@BergFulton We'll always be cool, no matter who notices. ;-)

**Comment by whit537** [comment]
> I’d be delighted to visit some time, but there are outstanding ‘hubbers in your area!

@raganwald Unbeknownst to me! :scream: What's the best way to proceed with setting something up?

**Comment by whit537** [comment]
Cooled off. Closing for now.
