### ISSUE TITLE
Group Mailer

### ISSUE THREAD

**Issue by renaantosz** [Ambridge/Ambridge#42]
Hello. I have a question about the group mailer that the chamber offered back in the fall. It was my understanding that you didn't have enough people to send out the fliers in the fall, which is fine, but it's been a few months now, so I was wondering what we can do to get these things out (I think it's a fantastic idea) or will you be issuing refunds? Thanks!
~Rena

**Comment by Hiznolly** [comment]
Rena
I will have Shawn, our director,  contact you directly.  The only mailer I recall was handled by Roberta and was sent out.  So I am not sure of what you are referring to.  
-Paul

**Comment by renaantosz** [comment]
Hey Paul, 
The mailer that was presented to us at the general meeting that was held at Do It Best last fall. It was being handled by a local printer, and it was supposed to go out to areas including Economy and Leetsdale. I spoke with Shawn around Christmas, and he said there weren't enough people to fill the spots yet and it would be revisited after the new year. I was under the impression that we would get a mock up before it was sent out to make sure all of our info was correct and we liked the way our ad looked, pretty standard. I haven't heard anything about it since then. If it has gone out, it would have been helpful to know as we put a coupon on our space, and I haven't recieved any back, so I know for future reference what sorts of advertising works and what doesn't for my business. I'm not angry or anything, I'm just trying to figure out what's going on. Thanks.
~Rena

**Comment by Hiznolly** [comment]
I just called Shawn and he is call you immediately.  Sorry for any inconvenience, it should have been addressed sooner.  
-Paul

**Comment by whit537** [comment]
@renaantosz Did you and Shawn figure this out the other day? What's the update? Can this be closed now?

**Comment by sanderson70** [comment]
Chad, I advised Rena that we will be using that mailer as an advertising
opportunity for 50th Annual Nationality Days begins.

On Mon, Feb 23, 2015 at 1:04 PM, Chad Whitacre <notifications@github.com>
wrote:

> @renaantosz <https://github.com/renaantosz> Did you and Shawn figure this
> out the other day? What's the update? Can this be closed now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ambridge/Ambridge/issues/42#issuecomment-75596636>.
>



-- 

*Shawn Anderson*
*Interim Director*
*Ambridge Area Chamber of Commerce*
562 Merchant Street || Ambridge, PA 15003
724-266-3040 (Phone)
ambridgechamberofcommerce.com
*Building Bridges to a Better Community!*

**Comment by Hiznolly** [comment]
Shawn, please return Rena's money and we will start over when offer starts again for Nationality Days.

**Comment by Hiznolly** [comment]
This can be closed now.

**Comment by renaantosz** [comment]
Shawn explained his strategy to me, we're all good.

**Comment by whit537** [comment]
Huzzah! :-)
