### ISSUE TITLE
add cardboard to Ambridge recycling program

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#48]
Per @jmkauer at https://github.com/Ambridge/Ambridge/issues/47#issuecomment-76458392, curb-side pickup doesn't include cardboard. This ticket is about expanding the Borough of Ambridge curb-side recycling program to include cardboard.

**Comment by jmkauer** [comment]
Hi Chad-

The Borough's Trash / Recycling Contract is to expire in December of this
year.  The Borough will have to solicit bids for this service very soon.
We can incorporate this into the spec's and see where costs come in at.

As for posting a detailed recycling list on the website; no issue there.
We'll get it up there soon and I'll report back.

Thanks!
Joe Kauer
Borough Manager

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Thanks very much, Mr. Kauer!

**Comment by derbwhite** [comment]
How do we increase participation in the recycling program?  There are only two households on my block that recycle, and we are one of them.  Increasing what items are accepted is one thing, but not so helpful if only 5-10% of the residents are participating.

**Comment by jmkauer** [comment]
The best practice would be a public education program.  We can include
something in our next Newsletter.  This maybe something we look at when we
redo our trash collection contract this summer.  The Borough has made a
grant request to the DEP for technical assistance in improving our trash /
recycling contract, so this is something we will certainly aim to improve
during that process.  Thank you.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Good point, @derbwhite. Reticketed as #53.

**Comment by sbdavies** [comment]
Per the Ambridge Borough website, cardboard is now recyclable. Yay!

http://www.ambridgeboro.org/vertical/sites/%7B00DC4E27-C97F-4CBE-BC9D-7D8801E8C52E%7D/uploads/Ambridge_Recycle_Flyer_11_18_15(2).pdf

**Comment by whit537** [comment]
@sbdavies May I add you as a manager on GitHub? That way you can close issues like this one. :-)

**Comment by sbdavies** [comment]
Sure!

**Comment by whit537** [comment]
@sbdavies Invite sent! :)

**Comment by whit537** [comment]
👍
