### ISSUE TITLE
Questions on  Rented vs Owned, Shade Tree , and Code Enforcement 

### ISSUE THREAD

**Issue by weallhave24hrs** [Ambridge/Ambridge#49]
Is there possible discussion to restrict the number of homes that can be rented out vs owned?

How can I get involved with the Shade Tree Commission?  

Is there discussion of making the Code Enforcement Officer becoming full time?

Answers:

1)  There can not be a limit on the number of homes that can be rented vs. owned in the Borough.  That would be discriminatory.  The Borough does have a Rental Property Inspection and Registration Program though.

2)  There is one open seat on the Tree Commission, it is a 5 year term.  If interested, please submit a letter of interest and resume to the Borough Office, attention Joe Kauer

3)   Code Officer was made full-time by Borough Council in January, 2015.

Thanks!
Joe

Joseph Kauer
Borough Manager
BOROUGH OF AMBRIDGE
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Thanks for posting here, @weallhave24hrs. It's helpful to have items like this go through GitHub to notify citizens and encourage sharing info. Gonna go ahead and click "Close" because I believe these are all addressed. Correct me if I'm wrong.
