### ISSUE TITLE
make Ambridge pedestrian-friendly

### ISSUE THREAD

**Issue by kjc3tacoma** [Ambridge/Ambridge#50]
I live on 15th Street and find it very annoying and very dangerous how many cars ignore the stop sign on the corner of 15th and Lenz.  Sometimes there is not even an pause and the cars go thru the intersection at speeds that must be near 35-40 MPH.  I cringe when i see kids riding bikes or playing in fear of them being struck by one of these cars.  I believe the police could make some funds and also make it known that this area needs policed for these offenders.  Especially when the weather warms up and folks are out and about.

**Comment by BergFulton** [comment]
I can definitely second this- as a runner I've had more than a few close calls in this intersection.

**Comment by kjc3tacoma** [comment]
Yes, it's a great street as far as our neighbors and folks take pride in their properties for the most part.  But that intersection is certainly a concern.

**Comment by jmkauer** [comment]
Good Afternoon-

Your concern about this intersection at 15th and Lenz has been forwarded to
the Ambridge Police Department so they can review and monitor this
location.  Thanks for your concerns.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by kjc3tacoma** [comment]
Thank you Joe!  The response time was great and i appreciate you forwarding this information.  I know the police have bigger fish to fry but they certainly could put some money in their coffers by monitoring that intersection.  Especially in the warmer months.

**Comment by whit537** [comment]
@kjc3tacoma Sounds like you're good to close this ticket? If not let me know. :-)

**Comment by whit537** [comment]
Actually ...

**Comment by whit537** [comment]
The general issue here was also raised by @eileenford on #25, and seconded by @goldbug:

> This isn't a major undertaking, or it certainly shouldn't be. I'm talking about police who are already on the job, one or two days a month, for 3 or 4 hours a day, trapping and writing citations. They (the police) don't need to be out there constantly, and they could pick good weather days for all I care. Do that 3 or 4 times and word will get out that Ambridge police are serious about enforcing pedestrian right of ways. It's not the number of tickets written, it's being visable and writing tickets just a few times to do the trick.

What kind of visibility do we have into how police are spending their time? Do our police keep timesheets? Are reports available to the public?

**Comment by whit537** [comment]
It seems to me that the two metrics we could use to track improvement in this area are:

 - time spent in enforcing pedestrian right of ways
 - number of citations issued for violating pedestrian right of ways

**Comment by goldbug** [comment]
My 'metric' would be not being forced up on the sidewalk or onto private property when I go for a run.  I don't give a hoot how many citations are issued or how much time the police spend on it.  None of the Beaver County river towns are pedestrian friendly, but Ambridge and it's motorist' are in a class of rude all by themselves.  They're not just ignoring pedestrian right of ways, but actually hostile towards walkers.

**Comment by whit537** [comment]
> My 'metric' would be not being forced up on the sidewalk or onto private property when I go for a run.

@goldbug Yes! So how do we get there? What are the incremental steps that will bring us to the point where you (and @eileenford and @kjc3tacoma and @BergFulton and ... and ...) are satisfied that Ambridge is pedestrian-friendly, and we can close this ticket?

**Comment by whit537** [comment]
One thing I would love to see would be a proper walk/bike trail that runs the whole length of town. I think we're selling ourselves short with this Ohio River Trail initiative if we just end up with bike path signs painted on Maplewood.

**Comment by kjc3tacoma** [comment]
Kudos to the Ambridge Police and to Joseph Kauer for their quick response to my request for oversight of the intersection at 15th and Lenz!  Yesterday my neighbor informed me of a police cruiser patrolling the intersection.  She spoke with him and thanked him.  Great to see the communication between the towns management and police.  Very well done!

**Comment by whit537** [comment]
@kjc3tacoma Nice!

I've reticketed the walk/bike route through town as #57.

**Comment by whit537** [comment]
"[What America’s Most Walkable Suburb Can Teach Towns Everywhere](http://www.shareable.net/blog/what-america%E2%80%99s-most-walkable-suburb-can-teach-towns-everywhere)"

What lessons can we learn from this article?

**Comment by whit537** [comment]
Closing this as over-broad. Let's reticket more specific ideas.
