### ISSUE TITLE
patch potholes on Maplewood 8th to 11th

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#55]
@JessWhit reports that @mmikul suggested at last night's council meeting that we use GitHub to report potholes around town. I noticed today that some streets have been patched already. We had really bad potholes in front of our house from the utility work that was done between Center for Hope and the park&mdash;that's fixed now, thankfully.

I'd like to report that Maplewood between 8th and 11th still needs to be patched. There are pretty bad potholes at the entrance to Maplewood off of 8th, and the potholes continue the whole stretch to 11th. I'm sure it's on the list but since it came up last night to report them here I figured I'd oblige! Keep up the good work, works crew! :-) :construction:

**Comment by jmkauer** [comment]
Good Morning!

Ambridge Public Works is active filling potholes.  There are two seperate
crews going around town addressing this concern and need.  I have made the
Foreman aware of the potholes on Maplewood.

Thanks,

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Thanks @jmkauer! :-)

**Comment by SethWhitacre** [comment]
Between 5th and 6th needs to be patched up as well

**Comment by jmkauer** [comment]
Good Morning!  Ambridge Public Works Department is currently on Maplewood
addressing potholes today.  Thanks for your patience and cooperation.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Confirmed, @jmkauer! Drove it this morning and saw fresh asphalt.

Keep up the good work! :-)
