### ISSUE TITLE
Plans for Earth Day clean up?

### ISSUE THREAD

**Issue by BergFulton** [Ambridge/Ambridge#58]
Just thinking because Earth Day is coming soon on April 22, and the receding snow has revealed a lot of trash, if there's not already plans for a community clean up, can we get that moving? The 22nd falls on a Wednesday, but what about the weekend before or after?

**Comment by whit537** [comment]
Surely the Committee to Clean and Beautify Ambridge has something planned. I believe Trinity Seminary has participated in the past as well.

**Comment by jmkauer** [comment]
Event info has been posted on the Borough website:
http://www.ambridgeboro.org/index.asp?Type=B_EV&SEC={D1E7E06C-B798-4225-A954-7249F8449EB5}&DE={7D882B40-DAD7-4F5C-9180-C410852F4844}


Also on our facebook page - "Borough of Ambridge"    Please like and follow
us for latest information and events.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org
