### ISSUE TITLE
patch potholes on Glenwood Drive above 3rd Street

### ISSUE THREAD

**Issue by Rdonnelly45** [Ambridge/Ambridge#61]
There are a bunch of potholes on Glenwood Drive above 3rd Street leading up to the big curve and a couple on the big curve (before Elm Road / Wilson Ave). Please patch. Thanks!

**Comment by Rdonnelly45** [comment]
@jmkauer @whit537 (not sure how to add labels for Ambridge and Public Works, hence the tagging, thanks guys!)

**Comment by whit537** [comment]
Thanks @Rdonnelly45. I've added the labels for you (permissions issue, sorry).

**Comment by jmkauer** [comment]
Good Morning, I'll advise the Public Works Department of these potholes so
they can be filled.

Thanks,
Joe


Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by whit537** [comment]
Any update on this @jmkauer? Is the Works Department still on pothole detail?

**Comment by Rdonnelly45** [comment]
They have not been filled yet up here by the way.

**Comment by jmkauer** [comment]
DPW is working their way up to that area.  There is a delay due to the
rain; potholes can't be patched in the rain.  Should be addressed within
the week.

Thanks,

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by jmkauer** [comment]
UPDATE:  Ambridge Public Works was on Glenwood yesterday repairing
potholes.  There are some more they still have to get, but they are
continuing to address the concerns.  Thanks for your patience.

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Thanks, @jmkauer! 

I am sorry if this has been asked already, but is the borough responsible for Duss Ave between 3rd and 5th? Or is that state maintained? There are a lot of potholes there.

**Comment by jmkauer** [comment]
That section of Duss is a Borough road, the DPW is aware of the condition
and is working to address those potholes as well.



Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Avenue
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Great, thank you!

**Comment by Rdonnelly45** [comment]
Thanks @jmkauer, looks like they finished addressing all the potholes around Glenwood Drive. Closing issue.

**Comment by whit537** [comment]
Huzzah! Duss between 3rd and 5th reticketed as #64.
