### ISSUE TITLE
patch potholes on Duss between 3rd and 5th

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#64]
Reticketing from https://github.com/Ambridge/Ambridge/issues/61#issuecomment-91601315.

cc: @sbdavies

**Comment by Rdonnelly45** [comment]
I drove over this segment of Duss today. All potholes patched. Hooray! Closing issue. @jmkauer @sbdavies

**Comment by sbdavies** [comment]
That's great! Thanks!
