### ISSUE TITLE
Street light needs replaced on Glenwood Drive

### ISSUE THREAD

**Issue by Rdonnelly45** [Ambridge/Ambridge#66]
Hi @jmkauer, the street light across from 12 Glenwood Drive needs replaced. It cycles off every few minutes all night long so the bulb and/or ballast must be reaching end-of-life. This street light is located exactly where the guard rail meets the metal fence at the big curve on Glenwood Drive (across from address 12). Thanks!

**Comment by jmkauer** [comment]
Hi Ryan-

We'll notify Duquesne Light today.  Thanks for letting us know.

Joe

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Street
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
I was just about to start a thread about street lights - thanks, Ryan! The street lights on the 800 block of Pine Street do the same thing - cycling on and off every few minutes. It gets extremely dark back there. The last time I walked up Eighth Street in the dark, a few of those lights were out as well - but they may be fixed by now.

**Comment by Rdonnelly45** [comment]
This street light is no longer intermittent... now it's completely dead.  Not sure if anything further can be done if Duquesne Light has already been notified.  This is at the big curve on Glenwood Dr. heading up to Ridge Rd.  Cars have a tendency to travel down the center of the road going both directions and can't see each other coming until the very last second.  It's dangerous even during the day.  Also, pedestrians can't see a thing while walking after dark around this corner.

**Comment by Rdonnelly45** [comment]
I called Duquesne Light myself as a residential customer last week and reported the street light completely out.  They fixed it about 3 days later.  Hooray!

**Comment by whit537** [comment]
Nice!
