### ISSUE TITLE
July Ambridge Borough Council Meeting Agenda

### ISSUE THREAD

**Issue by jmkauer** [Ambridge/Ambridge#79]
The Agenda for the July Meeting (Tuesday, 7/12/16) of Ambridge Borough Council has been posted online at:  http://www.ambridgeboro.org/index.asp?Type=B_BASIC&SEC={C02D21A9-F450-4BE1-BAD3-C5E429F6F782}

**Comment by sbdavies** [comment]
Thanks, @jmkauer! How long do the council meetings usually last? I would like to speak on the animal ordinances, but I work until 7:30 that day.

**Comment by jmkauer** [comment]
Public Comment is only taken at the beginning of the meetings
(approximately 7:00-7:15ish).  Meetings typically last 1 - 2 hours.

Joe



Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Street
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Ok, thanks! Maybe I can get someone to go on my behalf.

**Comment by jmkauer** [comment]
​If you can't make the meeting, you can email me what you'd like to share
with Council in advance of the meeting.  I can be sure to pass it along to
them.

Joe​

Joseph Kauer
*Borough Manager*
*BOROUGH OF AMBRIDGE*
600 Eleventh Street
Ambridge, PA  15003
P:  724-266-4070
F:  724-266-9191
www.AmbridgeBoro.org

**Comment by sbdavies** [comment]
Thanks very much, @jmkauer! I'm working on it now.

**Comment by sbdavies** [comment]
Thanks again @jmkauer! I'm about to email it to you.
