### ISSUE TITLE
hold Community Engagement meeting on January 22

### ISSUE THREAD

**Issue by whit537** [Ambridge/Ambridge#9]
We're doing this at the Library. What time? I don't see it on the Ambridge Connection calendar (and I'm not finding how to add an event there).

cc: @weallhave24hrs

**Comment by whit537** [comment]
Found it: http://www.ambridgeconnection.com/sumbitevent.html.

**Comment by whit537** [comment]
I submitted an AC calendar event for this

**Comment by whit537** [comment]
I submitted it as 7pm to 8:30pm because I think that's what we did before?

**Comment by weallhave24hrs** [comment]
You're invited 
to the January Community Engagement Meeting 

Moderator: local start up Gratipay
Location: Laughlin Memorial Library in Ambridge (downstairs auditorium)
When: This Thursday, Jan. 22 
Time: 7pm 

Why: Participate in an informal progressive conversation on community matters with local leaders, business owners, and residents. 

Is your community group or organization interested in hosting future meetings or being the moderator ? Contact Felicia at Ambridge Connection dot com

**Comment by BergFulton** [comment]
Can't come- running a bit behind in getting home. Let me know what's up and feel free to share my contact info for the slide scanning project!

**Comment by whit537** [comment]
No worries, @BergFulton. Slide scanner person wasn't there either.

Next meeting ticketed as #28.
